/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/outline/bible/brainstorm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Brainstorm Bible */
    post: operations["brainstorm_bible_outline_bible_brainstorm_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/outline/bible/create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Bible */
    post: operations["create_bible_outline_bible_create_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/outline/bible/{bible_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Bible */
    get: operations["get_bible_outline_bible__bible_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/outline/substory/brainstorm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Brainstorm Substory */
    post: operations["brainstorm_substory_outline_substory_brainstorm_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/outline/substory/create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Substory */
    post: operations["create_substory_outline_substory_create_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/outline/substory/{substory_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Substory */
    get: operations["get_substory_outline_substory__substory_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/materials/mine": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mine Materials */
    post: operations["mine_materials_materials_mine_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/materials/search/semantic": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Search Materials Semantic */
    post: operations["search_materials_semantic_materials_search_semantic_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/materials/search/lexical": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Search Materials Lexical */
    post: operations["search_materials_lexical_materials_search_lexical_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chapters": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start Chapter */
    post: operations["start_chapter_chapters_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chapters/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Chapter Run Status */
    get: operations["get_chapter_run_status_chapters_runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Bible */
    Bible: {
      /** Title */
      title: string;
      /** Logline */
      logline: string;
      /** Marketing Hook */
      marketing_hook: string;
      /** Worldview Tone */
      worldview_tone: string;
      /** Main Conflict */
      main_conflict: string;
      /** Ending Vision */
      ending_vision: string;
      /** Key Roles Summary */
      key_roles_summary: string;
    };
    /** BibleResponse */
    BibleResponse: {
      bible: components["schemas"]["Bible"];
    };
    /** BrainstormBibleRequest */
    BrainstormBibleRequest: {
      /** History */
      history?: string[];
      /** User Input */
      user_input: string;
    };
    /** BrainstormResponse */
    BrainstormResponse: {
      /** Content */
      content: string;
    };
    /** BrainstormSubstoryRequest */
    BrainstormSubstoryRequest: {
      /** History */
      history?: string[];
      /** User Input */
      user_input: string;
      /** Bible Id */
      bible_id: string;
    };
    /** ChapterRunStatusResponse */
    ChapterRunStatusResponse: {
      /** Id */
      id: string;
      status: components["schemas"]["WorkflowStatus"];
      current_stage: components["schemas"]["WorkflowStage"];
      /** Bible Id */
      bible_id: string;
      /** Substory Id */
      substory_id: string;
      /** Chapter Index */
      chapter_index: number;
      /** Substory Chapter Index */
      substory_chapter_index: number;
      error_code: components["schemas"]["WorkflowErrorCode"] | null;
      /** Error Message */
      error_message: string | null;
      /**
       * Started At
       * Format: date-time
       */
      started_at: string;
      /** Finished At */
      finished_at: string | null;
    };
    /** CreateBibleRequest */
    CreateBibleRequest: {
      /** Messages */
      messages: string[];
    };
    /** CreateBibleResponse */
    CreateBibleResponse: {
      /** Bible Id */
      bible_id: string;
    };
    /** CreateSubstoryRequest */
    CreateSubstoryRequest: {
      /** Bible Id */
      bible_id: string;
      /** Substory Order Index */
      substory_order_index: number;
      /** Messages */
      messages: string[];
    };
    /** CreateSubstoryResponse */
    CreateSubstoryResponse: {
      /** Substory Id */
      substory_id: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LexicalSearchMaterialsRequest */
    LexicalSearchMaterialsRequest: {
      /** Query */
      query?: string | null;
      /**
       * Limit
       * @default 8
       */
      limit: number;
      category?: components["schemas"]["MaterialCategory"] | null;
      mood?: components["schemas"]["MaterialMood"] | null;
      /** Tags */
      tags?: string[] | null;
    };
    /** @enum {string} */
    MaterialCategory: "对话" | "动作" | "心理" | "环境" | "外貌" | "意象";
    /** @enum {string} */
    MaterialMood: "喜悦" | "悲伤" | "愤怒" | "恐惧" | "温情" | "压抑" | "激昂" | "平静";
    /** MaterialSnippet */
    MaterialSnippet: {
      /**
       * Essential Text
       * @description 从文章中摘录的文本，20-100字
       */
      essential_text: string;
      /** @description 摘录文本的描写技法 */
      category: components["schemas"]["MaterialCategory"];
      /** @description 摘录文本的情绪基调 */
      mood: components["schemas"]["MaterialMood"];
      /**
       * Tags
       * @description 摘录文本的内容标签，如场景、情节、主题等
       */
      tags: string[];
    };
    /** MaterialsSearchResponse */
    MaterialsSearchResponse: {
      /** Snippets */
      snippets?: components["schemas"]["MaterialSnippet"][];
    };
    /** MineMaterialsRequest */
    MineMaterialsRequest: {
      /** Full Text */
      full_text: string;
    };
    /** MineMaterialsResponse */
    MineMaterialsResponse: {
      /** Created Snippet Count */
      created_snippet_count: number;
    };
    /** SemanticSearchMaterialsRequest */
    SemanticSearchMaterialsRequest: {
      /** Query */
      query: string;
      /**
       * Limit
       * @default 8
       */
      limit: number;
      category?: components["schemas"]["MaterialCategory"] | null;
      mood?: components["schemas"]["MaterialMood"] | null;
    };
    /** StartChapterRequest */
    StartChapterRequest: {
      /** Bible Id */
      bible_id: string;
      /** Substory Id */
      substory_id: string;
      /** Chapter Index */
      chapter_index: number;
      /** Substory Chapter Index */
      substory_chapter_index: number;
    };
    /** StartChapterResponse */
    StartChapterResponse: {
      /** Workflow Run Id */
      workflow_run_id: string;
    };
    /** Substory */
    Substory: {
      /** Substory Title */
      substory_title: string;
      /** Logic Nodes */
      logic_nodes: components["schemas"]["SubstoryActionNode"][];
      /** Core Conflict */
      core_conflict: string;
      /** Status Change */
      status_change: string;
    };
    /** SubstoryActionNode */
    SubstoryActionNode: {
      /** Cause */
      cause: string;
      /** Process */
      process: string;
      /** Effect */
      effect: string;
      /** Exchange */
      exchange: string;
      /** Context */
      context?: string | null;
    };
    /** SubstoryResponse */
    SubstoryResponse: {
      substory: components["schemas"]["Substory"];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * WorkflowErrorCode
     * @enum {string}
     */
    WorkflowErrorCode:
      | "llm_call_error"
      | "parse_error"
      | "sqlite_write_error"
      | "vector_write_error"
      | "context_too_long";
    /**
     * WorkflowStage
     * @enum {string}
     */
    WorkflowStage:
      | "load_context"
      | "generate_blueprint"
      | "generate_outline"
      | "generate_writing"
      | "generate_summary"
      | "generate_cumulative_summary";
    /**
     * WorkflowStatus
     * @enum {string}
     */
    WorkflowStatus: "pending" | "running" | "succeeded" | "failed" | "waiting_approval";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  brainstorm_bible_outline_bible_brainstorm_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BrainstormBibleRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BrainstormResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_bible_outline_bible_create_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBibleRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateBibleResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_bible_outline_bible__bible_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bible_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BibleResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  brainstorm_substory_outline_substory_brainstorm_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BrainstormSubstoryRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BrainstormResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_substory_outline_substory_create_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSubstoryRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateSubstoryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_substory_outline_substory__substory_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        substory_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubstoryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  mine_materials_materials_mine_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MineMaterialsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MineMaterialsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_materials_semantic_materials_search_semantic_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SemanticSearchMaterialsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MaterialsSearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_materials_lexical_materials_search_lexical_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LexicalSearchMaterialsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MaterialsSearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_chapter_chapters_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartChapterRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StartChapterResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_chapter_run_status_chapters_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChapterRunStatusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
